"""add cost_incurred to usage table

Revision ID: e00d004a7dd3
Revises: add_razorpay_fields
Create Date: 2026-05-07 14:55:13.751406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00d004a7dd3'
down_revision = 'add_razorpay_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('features_json', sa.Text(), nullable=True))

    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_incurred', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.drop_column('cost_incurred')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('features_json')
        batch_op.drop_column('plan_type')

    # ### end Alembic commands ###
